name: zookeeper
icon: zookeeper
type: datastore
title: ZooKeeper
endpoints:
- name: zookeeper
  ports:
  - name: zookeeper
    number: 2181
    protocol: tcp
options:
- version: '3.9'
  tag: '3.9'
labels:
- zookeeper

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/zookeeper
  chart: oci://registry-1.docker.io/wodby/zookeeper
  version: 0.1.0
  values:
  - name: resourcesPreset
    value: 'none'

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm:
    labels: persistence.labels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
  kind: statefulset
  primary: true
  helm:
    labels: commonLabels
    annotations: commonAnnotations
    volumes: extraVolumes
  containers:
  - name: zookeeper
    image: wodby/zookeeper
    helm:
      resources: resources
      env: extraEnvVars
      mounts: extraVolumeMounts
